### ISSUE TITLE
AutoSavePluginConfig中嵌套data class无法使用ValueDescription指定配置说明

### ISSUE THREAD

**Issue by StageGuard** [mamoe/mirai#1825]
如：
```kotlin
object PluginConfig : AutoSavePluginConfig("Config") {
    @ValueDescription("desc1")
    val key by value(0)
    val nested by value<NestedConfig>()
}

@Serializable
data class NestedConfig(
    @ValueDescription("desc2")
    val key: String = "value"
)
```

生成的config文件：
```yaml
# desc1
key: 0
nested: 
  key: value
```

虽然可以使用`net.mamoe.yamlkt:yamlkt`库的Comment来实现：
```kotlin
@Serializable
data class NestedConfig(
    @Comment("desc2")
    val key: String = "value"
)
```
```yaml
# desc1
key: 0
nested: 
  # desc2
  key: value
```
但是这样破坏了统一性，插件开发者希望都使用`ValueDescription`来注释(至少我是这么想的！)
